# apiVersion: "kubernetes-client.io/v1"
# kind: ExternalSecret
# metadata:
#   name: my-app-secret
# spec:
#   backendType: "systemManager" # set this to "ssm" for AWS SSM Parameter Store
#   data:
#     - key: "manishparameterstore"
#       name: "my-app-secret"
#       property: ""
#   template:
#     metadata:
#       name: my-secret-volume
#     spec:
#       secret:
#         secretName: my-app-secret      

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-app-secret
spec:
  backendType: systemManager
  data:
    - key: portal-db-postgres-dev-db-name
      name: db-name
      property: ""
    - key: portal-db-postgres-dev-url
      name: db-host
      property: ""
    - key: portal-db-postgres-dev-username
      name: db-user
      property: ""
  template:
    metadata:
      name: my-secret-volume
    spec:
      secret:
        secretName: my-app-secret